name = "belle-example-pkg"
version = "1.0.0"

title = "An incredible package for Isabelle"
date = 2026-03-27
abstract = """
This is an example of a `belle-pkg.toml` file for defining a package specification.
<br>
This may actually be sourced into Belle though <em>`belle source remote https://github.com/jcbyte/belle`</em>.
<br>
However this contains no Isabelle sessions, not even a <strong>ROOT</strong> file!
Meaning it will never be allowed to be added into an environment.
"""
licence = "AL2"
topics = ["Topic/Example", "Package Manger"]
note = "This is an optional note field"

# Other packages that this Isabelle component provides
# For when the ROOT file defines multiple sessions
provides = ["belle-example-pkg_Prereq"]

# List of compatible isabelle versions as SemVer listings
isabelles = ["2025.0.0", "2025.1.0", "2025.2.0"]


# Array of Tables for authors, containing given optional fields
[[authors]]
name = "Joel Cutler"
email = "joelcutler108@gmail.com"
orcid = "0000-0000-0000-0000"
homepages = ["https://joelcutler.dev"]

[[authors]]
name = "Exam Ple"
homepages = ["https://example.com/"]

# Array of Tables for contributors
[[contributors]]
name = "The White Rabbit"

# Dependencies required for the package and their versions
[dependencies]
"Z_Toolkit" = "2025.10.16"

# The 'extra' field allows for arbitrary nested data.
[extra]
# dois and pubs for AFP entries will be placed here
dois = ["00.00/00"]
pubs = ["https://example.com/"]
# Fields placed here are just example of arbitrary data
joel = 7
lang = "rust"
