name = "an-example-package"
version = "2026.0.0"
title = "An Incredible Isabelle Theory"
date = 2026-02-17
abstract = """
This is a multi-line string representing the abstract.
It can span multiple lines using triple quotes.
"""
licence = "BSD"
topics = ["Mathematics/Analysis", "Logic/Set theory"]
note = "Optional note field"

# Array of Tables for authors, containing given optional fields
[[authors]]
name = "Joel Cutler"
email = "joelcutler108@gmail.com"
orcid = "0000-0000-0000-0000"
homepages = ["https://joelcutler.dev"]

[[authors]]
name = "Exam Ple"
homepages = ["https://example.com/"]

# Array of Tables for contributors
[[contributors]]
name = "The White Rabbit"

# Dependencies required and their version
[dependencies]
"core-logic" = "2026.1.0"
"standard-lib" = "2025.2.0"

# Other packages that this Isabelle component provides
# For when the ROOT file defines multiple sessions
provides = ["another-package", "another-package-2"]

# List compatible isabelle versions
isabelles = ["2025.1.0", "2025.0.0"]

# The 'extra' field allows for arbitrary nested data. dois and pubs will be placed here
[extra]
dois = ["00.00/00"]
pubs = ["https://example.com/"]
priority = 10                   # This doesn't mean anything its just an example of arbitrary data
